//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int user_id { get; set; }
        public string user_login { get; set; }
        public string user_pass { get; set; }
        public string name_user { get; set; }
        public string surname { get; set; }
        public string patronomic { get; set; }
        public string bio { get; set; }
        public string status_login { get; set; }
        public byte[] picture { get; set; }
    }
}
